"""new migration

Revision ID: 01184113ef68
Revises: 79d7d8283f14
Create Date: 2025-05-02 19:18:15.694620

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '01184113ef68'
down_revision: Union[str, None] = '79d7d8283f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
