"""new migration

Revision ID: 45b1689f6b25
Revises: 316068a2468f
Create Date: 2025-05-06 14:29:16.419742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b1689f6b25'
down_revision: Union[str, None] = '316068a2468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_table('order_item')
    op.alter_column('ingredient', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingredient', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.alter_column('ingredient', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredient', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_item_order_id_fkey'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], name='order_item_pizza_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_item_pkey')
    )
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
