"""new migration

Revision ID: 568f800730cc
Revises: 9abeca3db4f6
Create Date: 2025-05-07 12:15:14.920527

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '568f800730cc'
down_revision: Union[str, None] = '9abeca3db4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
