"""new migration

Revision ID: 672c8b660383
Revises: 3f4be27fb6a4
Create Date: 2025-05-07 00:09:51.596083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672c8b660383'
down_revision: Union[str, None] = '3f4be27fb6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_ingredient_id', table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_table('pizza_ingredient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_ingredient',
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='pizza_ingredient_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], name='pizza_ingredient_pizza_id_fkey'),
    sa.PrimaryKeyConstraint('pizza_id', 'ingredient_id', name='pizza_ingredient_pkey')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ingredient_pkey')
    )
    op.create_index('ix_ingredient_id', 'ingredient', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_items_order_id_fkey'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], name='order_items_pizza_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
    )
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    # ### end Alembic commands ###
