"""new migration

Revision ID: cf267adf3140
Revises: 5bc16f17cee2
Create Date: 2025-05-02 19:29:32.801168

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'cf267adf3140'
down_revision: Union[str, None] = '5bc16f17cee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
