"""new migration

Revision ID: f7d229ba9f7d
Revises: d6e5213b9ffa
Create Date: 2025-05-07 12:17:43.027036

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f7d229ba9f7d'
down_revision: Union[str, None] = 'd6e5213b9ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
