name: Auto Update PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get list of commits
        id: commits
        run: |
          log=$(git log origin/${{ github.base_ref }}..HEAD --pretty=format:"- %s (%an)")
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          echo "log=$log" >> $GITHUB_OUTPUT

      - name: Update PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const body = pr.data.body || '';
            const updatedBody = body.replace(
              /%{all_commits}/g,
              `${{ steps.commits.outputs.log }}`
            );

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody,
            });
