name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
